# Generated by Django 4.0.3 on 2022-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('data', models.DateField()),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
